### ISSUE TITLE
New Version is not aot compatible and can't use static library

### ISSUE THREAD

**Issue by AhmedZero** [HexaEngine/Hexa.NET.ImGui#14]
In version 1.1.0, I can use the static library and NativeAOT. However, in version 2.0.0 and later, it uses reflections, making it incompatible with AOT, and I can’t depend on the static library too.

**Comment by JunaMeinhold** [comment]
Do you get an exception or a trim warning, because the static analyzers for aot don't report anything?

**Comment by AhmedZero** [comment]
https://github.com/dotnet/runtime/pull/104229
You use `Assembly.GetCallingAssembly`

**Comment by JunaMeinhold** [comment]
![image](https://github.com/user-attachments/assets/10ab6697-2f6e-4dcc-b2c4-47161803e46e)
Okay will be fixed soon...

**Comment by JunaMeinhold** [comment]
Closing this issue, tested it before uploading, if any other issue regarding aot persists just reopen the issue.

**Comment by AhmedZero** [comment]
The first issue is fixed, but I still can’t depend on the static library.
```xml
		<DirectPInvoke Include="cimgui" />
		<NativeLibrary Include="cimgui.lib" />
```
Reference:
https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/interop

**Comment by JunaMeinhold** [comment]
The wrapper depends on dynamic link libraries (.dll/so/dylib) and there are no cimgui.lib/a files i do not provide them.

**Comment by AhmedZero** [comment]
or create two seperated package the first, VTable with Dynamic Library and the second DLLImport with  Static Library.

**Comment by JunaMeinhold** [comment]
I currently don't have the motivation for doing it on my own, as i said if you want you can do a fork and make a pull request, the generator supports different modes for generating bindings (see https://github.com/HexaEngine/HexaGen/blob/7a1a3c664b55c7e98b2000c9f7df6caf4e9ecd4f/HexaGen/CsCodeGeneratorConfig.cs#L24) you just have to change that in the generator,json files located here https://github.com/HexaEngine/Hexa.NET.ImGui/blob/master/Generator/cimgui/generator.json (note each lib has it's own config file 4 in total).

DllImport and LibraryImport (which just generates a DllImport) is slow compared to the VTable method (I probably should use a different name, a api function table would be more accurate) when using normal C#.

**Comment by amerkoleci** [comment]
Hi,
Based on what concept LibraryImport and DllImport is slow? Did you benchmarked that?

**Comment by JunaMeinhold** [comment]
DllImport (LibraryImport is just DllImport) has the problem that it's lazy loaded means you always have checks on if it's loaded or not and loading it does again cause the whole system to stutter if you access one function the first time. Additionally there is memory fragmentation and CPU cache efficiency which is not guaranteed with DllImport since the function pointers could be stored somewhere but don't ask me where. I didn't do explicit benchmarks but i tested it on my engine's editor and the startup timing was about 1s less and CPU usage from the editor components where less than with DllImport, like from 0,44ms to 0,22ms.

**Comment by JunaMeinhold** [comment]
Additionally DllImport has a limitation in netstandard and can't be used for multiple platforms. Since on linux shared libs usually start with libXXX.so and on windows we have XXX.dll which often creates name differences and this becomes a problem when we try to load system libs, and setting NativeLibrary.SetDllImportResolver only works on .NET Core 3.0 or greater excluding netstandard versions and this would break .NET Framework compatibility. 

For this reason i close this issue as not planned.
